# Generated by Django 2.0 on 2017-12-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbtechlist',
            options={},
        ),
    ]
