# Generated by Django 2.0 on 2017-12-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171229_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbtechlist',
            options={'managed': False, 'ordering': ['employees', 'organization']},
        ),
    ]
