# Generated by Django 2.0 on 2018-01-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171229_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbtechlist',
            options={'ordering': ['-employees', 'organization']},
        ),
    ]
