# Generated by Django 2.0 on 2018-01-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180101_0312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sbtechlist',
            table=None,
        ),
    ]
