# Generated by Django 2.0 on 2018-01-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180101_0322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sbtechlist',
            table='sbtechlist',
        ),
    ]
